services:
  postgres:
    image: postgres:16
    container_name: library-app-db
    ports:
      - '5432:5432'
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/sql:/docker-entrypoint-initdb.d
#      - ./postgres/db_store:/var/lib/postgresql/data