spring:
  application:
    name: libraryApp
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: Asia/Tokyo
  # DB settings
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/libraryappdb
