/*
 * This file is generated by jOOQ.
 */
package yoshibata.exam.quocard.libraryApp.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import yoshibata.exam.quocard.libraryApp.jooq.tables.Author;
import yoshibata.exam.quocard.libraryApp.jooq.tables.Book;
import yoshibata.exam.quocard.libraryApp.jooq.tables.Work;
import yoshibata.exam.quocard.libraryApp.jooq.tables.records.AuthorRecord;
import yoshibata.exam.quocard.libraryApp.jooq.tables.records.BookRecord;
import yoshibata.exam.quocard.libraryApp.jooq.tables.records.WorkRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * library_app_schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> AUTHOR_PKEY = Internal.createUniqueKey(Author.AUTHOR, DSL.name("author_pkey"), new TableField[] { Author.AUTHOR.ID }, true);
    public static final UniqueKey<BookRecord> BOOK_PKEY = Internal.createUniqueKey(Book.BOOK, DSL.name("book_pkey"), new TableField[] { Book.BOOK.ID }, true);
    public static final UniqueKey<WorkRecord> WORK_PKEY = Internal.createUniqueKey(Work.WORK, DSL.name("work_pkey"), new TableField[] { Work.WORK.BOOK_ID, Work.WORK.AUTHOR_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<WorkRecord, AuthorRecord> WORK__WORK_AUTHOR_ID_FKEY = Internal.createForeignKey(Work.WORK, DSL.name("work_author_id_fkey"), new TableField[] { Work.WORK.AUTHOR_ID }, Keys.AUTHOR_PKEY, new TableField[] { Author.AUTHOR.ID }, true);
    public static final ForeignKey<WorkRecord, BookRecord> WORK__WORK_BOOK_ID_FKEY = Internal.createForeignKey(Work.WORK, DSL.name("work_book_id_fkey"), new TableField[] { Work.WORK.BOOK_ID }, Keys.BOOK_PKEY, new TableField[] { Book.BOOK.ID }, true);
}
