/*
 * This file is generated by jOOQ.
 */
package yoshibata.exam.quocard.libraryApp.JOOQ;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import yoshibata.exam.quocard.libraryApp.JOOQ.tables.Author;
import yoshibata.exam.quocard.libraryApp.JOOQ.tables.Book;
import yoshibata.exam.quocard.libraryApp.JOOQ.tables.Work;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LibraryAppSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>library_app_schema</code>
     */
    public static final LibraryAppSchema LIBRARY_APP_SCHEMA = new LibraryAppSchema();

    /**
     * The table <code>library_app_schema.author</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>library_app_schema.book</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * The table <code>library_app_schema.work</code>.
     */
    public final Work WORK = Work.WORK;

    /**
     * No further instances allowed
     */
    private LibraryAppSchema() {
        super("library_app_schema", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Author.AUTHOR,
            Book.BOOK,
            Work.WORK
        );
    }
}
