/*
 * This file is generated by jOOQ.
 */
package yoshibata.exam.quocard.libraryApp.JOOQ;


import yoshibata.exam.quocard.libraryApp.JOOQ.tables.Author;
import yoshibata.exam.quocard.libraryApp.JOOQ.tables.Book;
import yoshibata.exam.quocard.libraryApp.JOOQ.tables.Work;


/**
 * Convenience access to all tables in library_app_schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>library_app_schema.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>library_app_schema.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>library_app_schema.work</code>.
     */
    public static final Work WORK = Work.WORK;
}
